### ISSUE TITLE
mvp-cockpit: when installing S3 => Serious bug, ssh-agent not started while there was no error

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#105]
blueprint:
```
sshkey__demo:

g8client__env1:
    # url: 'du-conv-3.demo.greenitglobe.com'
    url: 'centrilogic.demo.greenitglobe.com'
    login: 'yves'
    password: '****'
    account: 'Account of Yves'

vdcfarm__vdcfarm1:

vdc__scality:
    vdcfarm: 'vdcfarm1'
    g8client: 'env1'
    # location: 'du-conv-3'
    location: 'centrilogic'

disk.ovc__disk1:
  size: 1000

s3__demo:
    vdc: 'scality'
    disk:
      - 'disk1'
    domain: 'mystorage.com'

actions:
  - action: 'install'
```

When executing `ays run`:
```
Error of job: fs.g8osfs!fuse (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 205, in client
    j.do._loadSSHAgent()
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 2322, in _loadSSHAgent
    "Serious bug, ssh-agent not started while there was no error, should never get here")
RuntimeError: Serious bug, ssh-agent not started while there was no error, should never get here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/fs.g8osfs/install.py", line 6, in action
    cuisine.package.mdupdate()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisinePackage.py", line 47, in mdupdate
    self._cuisine.core.run("apt-get update")
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1033, in run
    if "cygwin" in self.uname:
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1251, in uname
    self._uname = self._executor.execute("uname -a", showout=False)[1].lower()
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 251, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 177, in transport
    if self.client is None:
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 230, in client
    raise j.exceptions.RuntimeError(msg)
JSExceptions.RuntimeError: ERROR: Could not connect to ssh on root@172.98.207.213:2200. Error was: Serious bug, ssh-agent not started while there was no error, should never get here ((type:runtime.error)


******************************************************************************************

Error of job: app_docker!docker (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 205, in client
    j.do._loadSSHAgent()
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 2322, in _loadSSHAgent
    "Serious bug, ssh-agent not started while there was no error, should never get here")
RuntimeError: Serious bug, ssh-agent not started while there was no error, should never get here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/app_docker/install.py", line 7, in action
    if not cuisine.systemservices.docker.isInstalled():
  File "/opt/jumpscale8//lib/JumpScale/tools/cuisine/CuisineFactory.py", line 68, in isInstalled
    return self._cuisine.core.command_check(self.NAME)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1217, in command_check
    rc, out, err = self.run("which '%s'" % command, die=False, showout=False, profile=True)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1022, in run
    ppath = self._cuisine.bash.profilePath
  File "/opt/jumpscale8//lib/JumpScale/tools/bash/Bash.py", line 209, in profilePath
    self._profilePath = j.sal.fs.joinPaths(self.home, ".profile_js")
  File "/opt/jumpscale8//lib/JumpScale/tools/bash/Bash.py", line 146, in home
    for line in self._cuisine.core.run("printenv", profile=False, showout=False)[1].splitlines():
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1033, in run
    if "cygwin" in self.uname:
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1251, in uname
    self._uname = self._executor.execute("uname -a", showout=False)[1].lower()
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 251, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 177, in transport
    if self.client is None:
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 230, in client
    raise j.exceptions.RuntimeError(msg)
JSExceptions.RuntimeError: ERROR: Could not connect to ssh on root@172.98.207.213:2200. Error was: Serious bug, ssh-agent not started while there was no error, should never get here ((type:runtime.error)


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 261, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 5
 See stacktrace above to identify the issue ((type:runtime.error)
```

**Comment by rkhamis** [comment]
@yveskerwyn please close when verified
