### ISSUE TITLE
mvp-cockpit: error when using node.docker: docker-compose: command not found

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#114]
Blueprint used: http://172.98.207.199:82/ays81/ays81/Blueprints?ayspath=/optvar/cockpit_repos/yves03

```
g8client__cl:
  url: be-scale-1.demo.greenitglobe.com
  login: yves
  password: ****
  account: Account of Yves
```
```
vdc__vdc4docker:
  g8client: cl
  account: Account of Yves
  location: be-scale-1
```
```
node.ovc__vm4docker:
  description: 'vm for testing app_docker cl'
  bootdisk.size: 10
  memory: 2
  os.image: 'Ubuntu 16.04 x64'
  ports:
    - '7122:22'
    - '22:2210'
  vdc: vdc4docker
```
```
os.ssh.ubuntu__vm4docker:
  node: 'vm4docker'
```
```
app_docker__dockermachine:
  os: vm4docker
```
```
node.docker__container:
  image: 'ubuntu/xenial'
  hostname: vm4docker
  os: vm4docker
  ports:
    - '2210:22'
```

**Error**:
```
Error of job: node.docker!container (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/node.docker/install.py", line 26, in action
    code, _, err = cuisine.core.run('cd {} && docker-compose up -d'.format(base))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1061, in run
    raise j.exceptions.RuntimeError('%s, %s' % (cmd, err))
JSExceptions.RuntimeError: ERROR: cd /var/dockers/container && docker-compose up -d, bash: docker-compose: command not found
 ((type:runtime.error)


******************************************************************************************
```

**Comment by yveskerwyn** [comment]
When manually trying to fix the problem, I discovered that **docker.io/ubuntu/xenial** => 405

```
root@vm-355:~# cd /var/dockers/container
root@vm-355:/var/dockers/container# docker-compose up -d
Pulling container (ubuntu/xenial:latest)...
Pulling repository docker.io/ubuntu/xenial
ERROR: Error: image ubuntu/xenial:latest not found
```

**Comment by yveskerwyn** [comment]
Problem fixed by adding:
```
sshkey__main:
```

and referencing this key in both `node.ovc__vm4docker` and `os.ssh.ubuntu__vm4docker`
