### ISSUE TITLE
mvp-cockpit: Connection error when using node.docker

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#116]
Cockpit: 
```
ssh cloudscalers@172.98.207.199 -p7122 -A
```

Password is **iZASUo7tE**

**Blueprints**:

See `/optvar/cockpit_repos/yves04`

```
g8client__cl:
  url: be-scale-1.demo.greenitglobe.com
  login: yves
  password: ****
  account: Account of Yves
```

```
vdc__vdc4docker:
  g8client: cl
  account: Account of Yves
  location: be-scale-1
```

```
sshkey__main:

node.ovc__vm4docker:
  description: 'vm for testing app_docker cl'
  bootdisk.size: 10
  memory: 2
  os.image: 'Ubuntu 16.04 x64'
  ports:
    - '7122:22'
    - '22:2210'
  vdc: vdc4docker
  sshkey: 'main'
```

```
os.ssh.ubuntu__vm4docker:
  node: 'vm4docker'
  sshkey: main

app_docker__dockermachine:
  os: vm4docker
```

```
node.docker__container:
  image: 'visity/webdav'
  hostname: vm4docker
  os: vm4docker
  ports:
    - '2210:22'
```

**Error**:
```
Error of job: os.ssh.ubuntu!container (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/os.ssh.ubuntu/install.py", line 31, in action
    executor.cuisine.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineSSH.py", line 137, in authorize
    d = self._cuisine.user.check(user, need_passwd=False)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineUser.py", line 85, in check
    _, d, _ = self._cuisine.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1033, in run
    if "cygwin" in self.uname:
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1251, in uname
    self._uname = self._executor.execute("uname -a", showout=False)[1].lower()
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 251, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 179, in transport
    "Could not connect to %s:%s" % (self.addr, self.port))
JSExceptions.RuntimeError: ERROR: Could not connect to 85.255.197.114:22 ((type:runtime.error)


******************************************************************************************
```

**Comment by yveskerwyn** [comment]
When trying again, got a different error:

```
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/node.docker/install.py", line 26, in action
    code, _, err = cuisine.core.run('cd {} && docker-compose up -d'.format(base))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1061, in run
    raise j.exceptions.RuntimeError('%s, %s' % (cmd, err))
JSExceptions.RuntimeError: ERROR: cd /var/dockers/container && docker-compose up -d, bash: docker-compose: command not found
 ((type:runtime.error)


******************************************************************************************
```

**Comment by yveskerwyn** [comment]
not an AYS problem, problem was that the visity/webdav image doesn't expose port 22, thanks @muhamadazmy
