### ISSUE TITLE
Having to run an S3 actor install() twice

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#119]
The first time I executed `ays run` it fails with error below, when executing `ays run` again installation succeeds:

```
Error of job: os.ssh.ubuntu!s3server (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/os.ssh.ubuntu/install.py", line 31, in action
    executor.cuisine.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineSSH.py", line 137, in authorize
    d = self._cuisine.user.check(user, need_passwd=False)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineUser.py", line 85, in check
    _, d, _ = self._cuisine.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1033, in run
    if "cygwin" in self.uname:
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1251, in uname
    self._uname = self._executor.execute("uname -a", showout=False)[1].lower()
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 251, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 179, in transport
    "Could not connect to %s:%s" % (self.addr, self.port))
JSExceptions.RuntimeError: ERROR: Could not connect to :2200 ((type:runtime.error)


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 261, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 4
 See stacktrace above to identify the issue ((type:runtime.error)

```

**Comment by rkhamis** [comment]
should be solved by https://github.com/Jumpscale/jumpscale_core8/commit/9a6bdfd744302de8d2c53cca1e693cb5c0d0424b

**Comment by john-kheir** [comment]
## Environment
Verified on du-conv-3
## Version
8.1.0 rc1
