### ISSUE TITLE
list index out of range when executing ownCloud blueprint

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#123]
When executing `ays blueprint` using below blueprint, getting **IndexError** 

```
g8client__cl:
  url: centrilogic.demo.greenitglobe.com
  login: ****
  password: ****
  account: Account of Yves

vdc__vdc4owncloud:
  g8client: cl
  location: centrilogic

blueowncloud__owncloudserver:
  vdc: vdc4owncloud
  domain: 'mycloud.com'
  datadisks:
    - 1000
    - 1000

actions:
  - action: 'install'
```

```
**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 137, in blueprint
    repo.blueprintExecute(role=role, instance=instance, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 343, in blueprintExecute
    bp.load(role=role, instance=instance)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Blueprint.py", line 179, in load
    actor.serviceCreate(instance=bpinstance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 389, in serviceCreate
    service = Service(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 23, in __init__
    self._initFromActor(actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 103, in _initFromActor
    self._initProducers(actor, args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 190, in _initProducers
    available_services.append(auto_actor.serviceCreate(instance="auto_%s" % idx, args={}))
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 389, in serviceCreate
    service = Service(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 23, in __init__
    self._initFromActor(actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 92, in _initFromActor
    dbobj.data = j.data.capnp.getBinaryData(j.data.capnp.getObj(dbobj.dataSchema, args=args, name='Schema'))
  File "/opt/jumpscale8//lib/JumpScale/data/capnp/Capnp.py", line 119, in getObj
    schema = self.getSchemaFromText(schemaInText, name=name)
  File "/opt/jumpscale8//lib/JumpScale/data/capnp/Capnp.py", line 96, in getSchemaFromText
    schemas = self.getSchemas(schemaInText)
  File "/opt/jumpscale8//lib/JumpScale/data/capnp/Capnp.py", line 76, in getSchemas
    schemaId = self.getId(schemaInText)
  File "/opt/jumpscale8//lib/JumpScale/data/capnp/Capnp.py", line 70, in getId
    id = [item for item in schemaInText.split("\n") if item.strip() != ""][0][3:-1]
IndexError: list index out of range
```

**Comment by rkhamis** [comment]
@yveskerwyn just tried it and it works.
Are you sure you have latest?

**Comment by rkhamis** [comment]
Not an issue. Already fixed in latest.

**Comment by john-kheir** [comment]
## Verified on 8.1.0 rc1
