### ISSUE TITLE
Errors when executing owncloud blueprint

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/ays_jumpscale8#124]
Note: These blueprints can pass one time then fail for 10 times
## First Example
```
g8client__main:
    url: 'gig.demo.greenitglobe.com'
    login: '****'
    password: '****'
    account: 'john'


vdc__main5:
    g8client: 'main'
    description: 'des'
    location: 'be-conv-2'

blueowncloud__bc:
    vdc: 'main5'
    datadisks:
       - 1000
       - 1000
    domain: 'owndomain.com'
```
```
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/os.ssh.ubuntu/install.py", line 31, in action
    executor.cuisine.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineSSH.py", line 137, in authorize
    d = self._cuisine.user.check(user, need_passwd=False)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineUser.py", line 85, in check
    _, d, _ = self._cuisine.core.run("getent passwd | egrep '^%s:' ; true" % (name))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1033, in run
    if "cygwin" in self.uname:
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1251, in uname
    self._uname = self._executor.execute("uname -a", showout=False)[1].lower()
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 251, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 179, in transport
    "Could not connect to %s:%s" % (self.addr, self.port))
JSExceptions.RuntimeError: ERROR: Could not connect to :2200 ((type:runtime.error)


******************************************************************************************
```

## Second Example
```
```
g8client__env1:
    url: 'du-conv-3.demo.greenitglobe.com'
    #    url: 'gig.demo.greenitglobe.com'
    login: '****'
    password: '****'
    account: 'thabeta'

vdc__myspaceboc2:
    g8client: 'env1'
    location: 'du-conv-3'
    #location: 'be-conv-2'

blueowncloud__oc1:
    domain: 'supercloud.com'
    vdc: myspaceboc2
    datadisks:
        - 1000
        - 1000
```
Error of job: node.docker!owncloud (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 207, in client
    j.do.loadSSHKeys(self.key_filename)
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 2121, in loadSSHKeys
    keysloaded = [self.getBaseName(item) for item in self.listSSHKeyFromAgent()]
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 2188, in listSSHKeyFromAgent
    self._loadSSHAgent()
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 2317, in _loadSSHAgent
    "Could not start ssh-agent, something went wrong,\nstdout:%s\nstderr:%s\n" % (result, err))
RuntimeError: Could not start ssh-agent, something went wrong,
stdout:
stderr:bind: Address already in use
unix_listener: cannot bind to path: /root/sshagent_socket
```

**Comment by rkhamis** [comment]
First issue means you never got an ip. That's an openvcloud issue. Please confirm that's the case?

**Comment by john-kheir** [comment]
@rkhamis For first issue: not sure that the connection error because the vm didn't get ip.. but even if this is the case, usually the first vm in deployed cloudspace takes time to take ip .. so i think this should be handled in ays_jumpscale .. however you can check with @grimpy

**Comment by john-kheir** [comment]
Another issue:
```
Error of job: node.ovc!bc (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/node.ovc/install.py", line 84, in action
    ssdSize=disk_args.ssdSize)
TypeError: add_disk() got an unexpected keyword argument 'ssdSize'


******************************************************************************************
```

**Comment by rkhamis** [comment]
@john-kheir you need to use be-g8-4 or du-conv-3. These are the updated envs.

**Comment by john-kheir** [comment]
@rkhamis for last issue you are right

**Comment by john-kheir** [comment]
2nd issue happened again.
```
Error of job: fs.g8osfs!fuse (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 207, in client
    j.do.loadSSHKeys(self.key_filename)
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 2119, in loadSSHKeys
    self._loadSSHAgent()
  File "/opt/jumpscale8/lib/JumpScale/InstallTools.py", line 2317, in _loadSSHAgent
    "Could not start ssh-agent, something went wrong,\nstdout:%s\nstderr:%s\n" % (result, err))
RuntimeError: Could not start ssh-agent, something went wrong,
stdout:
stderr:bind: Address already in use
unix_listener: cannot bind to path: /root/sshagent_socket
```

**Comment by john-kheir** [comment]
## Note: The ssh-agent problem seems that it is fixed and that is good.
```
NO NEED TO ADD SSH_AUTH_SOCK to env
more than 1 ssh-agent, will kill all
load ssh agent
```
## However still the connection error occurs

```Error of job: tidb!tidb (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/tidb/install.py", line 8, in action
    cuisine.apps.tidb.start()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/JSCuisine.py", line 70, in apps
    self._apps = apps(self._executor, self)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/apps/apps.py", line 10, in __init__
    base.__init__(self, executor, cuisine)
  File "/opt/jumpscale8//lib/JumpScale/tools/cuisine/CuisineFactory.py", line 89, in __init__
    exec(do)
  File "<string>", line 1, in <module>
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/apps/CuisinePortal.py", line 14, in __init__
    self.portal_dir = j.sal.fs.joinPaths(self._cuisine.core.dir_paths["appDir"], "portals/")
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 234, in dir_paths
    env = self.getenv()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 215, in getenv
    _, out, _ = self._cuisine.core.run("printenv", profile=False, showout=False, replaceArgs=False)
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1033, in run
    if "cygwin" in self.uname:
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1251, in uname
    self._uname = self._executor.execute("uname -a", showout=False)[1].lower()
  File "/opt/jumpscale8/lib/JumpScale/tools/executor/ExecutorSSH.py", line 173, in execute
    rc, out, err = self.sshclient.execute(cmds2, die=die, showout=showout)
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 251, in execute
    ch = self.transport.open_session()
  File "/opt/jumpscale8//lib/JumpScale/clients/ssh/SSHClient.py", line 179, in transport
    "Could not connect to %s:%s" % (self.addr, self.port))
JSExceptions.RuntimeError: ERROR: Could not connect to :2201 ((type:runtime.error)

```

## Another new issue occured
```
Error of job: node.docker!owncloud (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/node.docker/install.py", line 26, in action
    code, _, err = cuisine.core.run('cd {} && docker-compose up -d'.format(base))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1061, in run
    raise j.exceptions.RuntimeError('%s, %s' % (cmd, err))
JSExceptions.RuntimeError: ERROR: cd /var/dockers/owncloud && docker-compose up -d, bash: docker-compose: command not found
 ((type:runtime.error)


******************************************************************************************

Error of job: node.docker!tidb (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/node.docker/install.py", line 26, in action
    code, _, err = cuisine.core.run('cd {} && docker-compose up -d'.format(base))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1061, in run
    raise j.exceptions.RuntimeError('%s, %s' % (cmd, err))
JSExceptions.RuntimeError: ERROR: cd /var/dockers/tidb && docker-compose up -d, bash: docker-compose: command not found
 ((type:runtime.error)


******************************************************************************************
```

**Comment by john-kheir** [comment]
GOOD JOB :D 
## Software Version
Verified on du-conv-2
