### ISSUE TITLE
mvp-cockpit: S3 actor fails with KeyError: 'pop from an empty set'

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#133]
Blueprint:
```
g8client__cl:
  url: uk-g8-1.demo.greenitglobe.com
  login: yves
  password: ****
  account: Account of Yves

vdc__vdc4s3:
  g8client: cl
  account: Account of Yves
  location: uk-g8-1

sshkey__main:

disk.ovc__disk1:
  size: 1000

s3__s3server:
  vdc: vdc4s3
  sshkey: main
  disk:
    - 'disk1'
  domain: 'mystorage.com'
  key.access: 'access'
  key.secret: 'secret'

actions:
  - action: 'install'
```

Result of `ays run`:
```
Error of job: fs.btrfs!data (autoscale):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/fs.btrfs/autoscale.py", line 36, in action
    disk_name = added.pop()
KeyError: 'pop from an empty set'


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 261, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 1
 See stacktrace above to identify the issue ((type:runtime.error)
```

**Comment by rkhamis** [comment]
Autoscale shouldn't have been part of the installation. Was this installation resumed after being partially installed?

**Comment by yveskerwyn** [comment]
no, blocked there

**Comment by john-kheir** [comment]
## Software Version
Verified on 8.1.0 rc1
