### ISSUE TITLE
Error during the execution of owncloud and scality blueprints

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/ays_jumpscale8#170]
## Version 
ays: 8.1.1
js8: 8.1.1
## Blueprint
```
g8client__main:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: ''
    password: ''
    account: 'test_8.1.1'

vdc__owncloud:
    g8client: 'main'
    location: 'du-conv-2'

blueowncloud__bc:
    vdc: 'owncloud'
    datadisks:
       - 1000
       - 1000
    hostprefix: 'testcloud'

# 'QA SERVICE' (THE TEMPLATE SHOULD HAS THIS LINE)
test_owncloud_install__tc:
    blueowncloud: 'bc'
    owncloud: 'own1'

actions:
    - action: 'install'
    - action: 'test'
      actor: 'test_owncloud_install'
```

## Error
```
Error of job: node.docker!owncloud (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/node.docker/install.py", line 29, in action
    code, _, err = cuisine.core.run('cd {} && docker-compose up -d'.format(base))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1074, in run
    raise j.exceptions.RuntimeError('%s, %s' % (cmd, err))
JSExceptions.RuntimeError: ERROR: cd /var/dockers/owncloud && docker-compose up -d, Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 560, in urlopen
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 354, in _make_request
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/docker/transport/unixconn.py", line 33, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by john-kheir** [comment]
# Same error with scality  
## Error
```
Error of job: node.docker!caddy (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/node.docker/install.py", line 29, in action
    code, _, err = cuisine.core.run('cd {} && docker-compose up -d'.format(base))
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisineCore.py", line 1074, in run
    raise j.exceptions.RuntimeError('%s, %s' % (cmd, err))
JSExceptions.RuntimeError: ERROR: cd /var/dockers/caddy && docker-compose up -d, Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 560, in urlopen
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 354, in _make_request
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/docker/transport/unixconn.py", line 33, in connect
    sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by john-kheir** [comment]
This issue specifically doesn't happen any more
Verified on 8.1.1
