### ISSUE TITLE
Can't acquire lock and multiple ssh-agents when running s3 and owncloud blueprints

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/ays_jumpscale8#185]
## ERROR for s3
```
Error of job: app_docker!docker (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 198, in start
    res = self.method(**self.args)
  File "/tmp/actions/app_docker/install.py", line 8, in action
    cuisine.systemservices.docker.install()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/systemservices/CuisineDocker.py", line 35, in install
    with FileLock(LOCK_NAME, locktimeout=LOCK_TIMEOUT):
  File "/opt/jumpscale8/lib/JumpScale/sal/fs/SystemFS.py", line 216, in __enter__
    lock(self.lock_name, reentry=self.reentry, locktimeout=self.locktimeout)
  File "/opt/jumpscale8/lib/JumpScale/sal/fs/SystemFS.py", line 82, in lock
    message="Cannot acquire lock [%s]" % (lockname))
JumpScale.sal.fs.SystemFS.LockTimeoutException: Cannot acquire lock [APT-LOCK]


******************************************************************************************

Error of job: fs.g8osfs!fuse (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 198, in start
    res = self.method(**self.args)
  File "/tmp/actions/fs.g8osfs/install.py", line 6, in action
    cuisine.package.mdupdate()
  File "/opt/jumpscale8/lib/JumpScale/tools/cuisine/CuisinePackage.py", line 52, in mdupdate
    with FileLock(LOCK_NAME, locktimeout=LOCK_TIMEOUT):
  File "/opt/jumpscale8/lib/JumpScale/sal/fs/SystemFS.py", line 216, in __enter__
    lock(self.lock_name, reentry=self.reentry, locktimeout=self.locktimeout)
  File "/opt/jumpscale8/lib/JumpScale/sal/fs/SystemFS.py", line 82, in lock
    message="Cannot acquire lock [%s]" % (lockname))
JumpScale.sal.fs.SystemFS.LockTimeoutException: Cannot acquire lock [APT-LOCK]


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 267, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 5
 See stacktrace above to identify the issue ((type:runtime.error)
```

And when i tried to check the ssh-agent , i got this:
```root@jumpscale8:/opt/code/s3test# ps aux | grep ssh-agent
root       386  0.0  0.0  11140   316 ?        Ss   09:07   0:00 ssh-agent -a /root/sshagent_socket
root       393  0.0  0.0  11140   320 ?        Ss   09:07   0:00 ssh-agent -a /root/sshagent_socket
root       615  0.0  0.0  11140   316 ?        Ss   09:12   0:00 ssh-agent -a /root/sshagent_socket
root       622  0.0  0.0  11140   316 ?        Ss   09:12   0:00 ssh-agent -a /root/sshagent_socket
root       629  0.0  0.0  11140   320 ?        Ss   09:12   0:00 ssh-agent -a /root/sshagent_socket
root       639  0.0  0.0  11140   316 ?        Ss   09:12   0:00 ssh-agent -a /root/sshagent_socket
root       940  0.0  0.0  11140   320 ?        Ss   09:30   0:00 ssh-agent -a /root/sshagent_socket
root       947  0.0  0.0  11140   320 ?        Ss   09:30   0:00 ssh-agent -a /root/sshagent_socket
root       954  0.0  0.0  11140   320 ?        Ss   09:30   0:00 ssh-agent -a /root/sshagent_socket
root       964  0.0  0.0  11140   320 ?        Ss   09:30   0:00 ssh-agent -a /root/sshagent_socket
root      1054  0.0  0.0  11140   316 ?        Ss   09:30   0:00 ssh-agent -a /root/sshagent_socket
root      1061  0.0  0.0  11140   320 ?        Ss   09:30   0:00 ssh-agent -a /root/sshagent_socket
root      1115  0.0  0.0  11140   316 ?        Ss   09:31   0:00 ssh-agent -a /root/sshagent_socket
root      1126  0.0  0.0  11140   320 ?        Ss   09:31   0:00 ssh-agent -a /root/sshagent_socket
root      1136  0.0  0.0  11140   320 ?        Ss   09:31   0:00 ssh-agent -a /root/sshagent_socket
root      1143  0.0  0.0  11140   320 ?        Ss   09:31   0:00 ssh-agent -a /root/sshagent_socket
root      1150  0.0  0.0  11140   320 ?        Ss   09:31   0:00 ssh-agent -a /root/sshagent_socket
root      1160  0.0  0.0  11140   320 ?        Ss   09:31   0:00 ssh-agent -a /root/sshagent_socket
root      1315  0.0  0.0  11140   320 ?        Ss   09:32   0:00 ssh-agent -a /root/sshagent_socket
root      1322  0.0  0.0  11140   320 ?        Ss   09:32   0:00 ssh-agent -a /root/sshagent_socket
root      1444  0.0  0.0  11140   320 ?        Ss   09:36   0:00 ssh-agent -a /root/sshagent_socket
root      1451  0.0  0.0  11140   320 ?        Ss   09:36   0:00 ssh-agent -a /root/sshagent_socket
root      1458  0.0  0.0  11140   320 ?        Ss   09:36   0:00 ssh-agent -a /root/sshagent_socket
root      1468  0.0  0.0  11140   320 ?        Ss   09:36   0:00 ssh-agent -a /root/sshagent_socket
root      1568  0.0  0.0  11140   316 ?        Ss   09:45   0:00 ssh-agent
root      1570  0.0  0.0  11284  1008 ?        S+   09:45   0:00 grep --color=auto ssh-agent
root     18378  0.0  0.0  11140   320 ?        Ss   Feb28   0:00 ssh-agent -s
root     32556  0.0  0.0  11140   316 ?        Ss   09:05   0:00 ssh-agent -a /root/sshagent_socket
root     32564  0.0  0.0  11140   320 ?        Ss   09:05   0:00 ssh-agent -a /root/sshagent_socket
root     32572  0.0  0.0  11140   320 ?        Ss   09:05   0:00 ssh-agent -a /root/sshagent_socket
root     32579  0.0  0.0  11140   320 ?        Ss   09:05   0:00 ssh-agent -a /root/sshagent_socket
root     32586  0.0  0.0  11140   316 ?        Ss   09:05   0:00 ssh-agent -a /root/sshagent_socket
root     32594  0.0  0.0  11140   320 ?        Ss   09:05   0:00 ssh-agent -a /root/sshagent_socket
root     32604  0.0  0.0  11140   320 ?        Ss   09:05   0:00 ssh-agent -a /root/sshagent_socket
root     32611  0.0  0.0  11140   320 ?        Ss   09:05   0:00 ssh-agent -a /root/sshagent_socket
root     32621  0.0  0.0  11140   320 ?        Ss   09:05   0:00 ssh-agent -a /root/sshag
```

## Version
 8.1.1

**Comment by ashraffouda** [comment]
https://github.com/Jumpscale/jumpscale_core8/commit/a88203e23a258e894dbbe26cde3765a1179b2e5d
