### ISSUE TITLE
ays blueprint, ays run, ays restore, all fail when after interrupted ays run

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#206]
See repository `dalius1` on [the Cockpit we use at Mauritius](https://ma-g8-1.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=2162)

Context:
- We have successfully executed `ays blueprint` on the repository containing only one blueprint, for deploying an ownCloud instance
- We could successfully launch `ays run`, but because of broken SSH connection the  installation didn't run to the finish
- When reconnecting to the Cockpit, and executing again `ays blueprint` we got this:

````
Error of job: vdc!daliusvdc1 (processChange):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 169, in executeInProcess
    res = self.method(job=self)
  File "/tmp/actions/vdc/processChange.py", line 33, in action
    create=False)
  File "/opt/jumpscale8//lib/JumpScale/clients/openvcloud/Client.py", line 241, in space_get
    "Could not find space with name %s" % name)
JSExceptions.RuntimeError: ERROR: Could not find space with name daliusvdc1 ((type:runtime.error)


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 137, in blueprint
    repo.blueprintExecute(role=role, instance=instance, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 432, in blueprintExecute
    actor._initFromTemplate(template)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 106, in _initFromTemplate
    self.processChange("dataschema")
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 369, in processChange
    service.processChange(actor=self, changeCategory=changeCategory)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 548, in processChange
    args = job.executeInProcess()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 179, in executeInProcess
    raise j.exceptions.RuntimeError("could not execute job:%s" % self)
JSExceptions.RuntimeError: ERROR: could not execute job:job: vdc!daliusvdc1 (processChange) ((type:runtime.error)
```

-  Also when trying `ays run` we got an error:

```
Error of job: vdc!daliusvdc1 (processChange):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 198, in start
    res = self.method(**self.args)
  File "/tmp/actions/vdc/processChange.py", line 8, in action
    category = args.pop('changeCategory')
KeyError: 'changeCategory'


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 271, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 1
 See stacktrace above to identify the issue ((type:runtime.error)
```

- Is this expected behaviour or a bug?
- If expected how can we recover from such a situation?

What I did was executing `ays destroy` and then again `ays blueprint` + `ays run`.

Is that the only way to recover?

**Comment by xmonader** [comment]
I believe you should redo `ays run` again to calculate the remaining steps and execute it.

For the broken SSH connections: as long as you're running through tmux/screen it won't be an issue.
