### ISSUE TITLE
Unexpected error when creating new account

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#225]
Tested on:
```
ssh cloudscalers@10.101.101.135 -p7122 (password: 4GgwKh3iB)
cd /optvar/cockpit_repos/account_test1
```

Blueprint:
```
g8client__cl:
  url: 'be-scale-1.demo.greenitglobe.com'
  login: 'cockpit_api_user'
  password: 'cockpit12345'
  account: 'Account of Artilium'

account__56e16382bc:
  g8client: 'cl'
  maxMemoryCapacity: 7
  maxCPUCapacity: 3
  maxNumPublicIP: 6
  maxDiskCapacity: 11
  description: 'Reseller 56e16382bc Created by newreseller'
actions:
  - action: install
```

Error when executing `ays run`: 
User 'cockpit_api_user' is the last admin on the account '56e16382bc'

Traceback:

```
Error of job: account!56e16382bc (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 196, in start
    res = self.method(**self.args)
  File "/tmp/actions/account/install.py", line 26, in action
    account.unauthorize_user(username=user)
  File "/opt/jumpscale8//lib/JumpScale/clients/openvcloud/Client.py", line 187, in unauthorize_user
    self._deleteUser(username)
  File "/opt/jumpscale8//lib/JumpScale/clients/openvcloud/Client.py", line 257, in _deleteUser
    self.client.api.cloudapi.accounts.deleteUser(accountId=self.id, userId=username, recursivedelete=True)
  File "/opt/jumpscale8/lib/JumpScale/clients/portal/PortalClient.py", line 43, in __call__
    raise ApiError(response)
JumpScale.clients.portal.PortalClient.ApiError: 400 Bad Request
User 'cockpit_api_user' is the last admin on the account '56e16382bc'


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/usr/local/bin/ays", line 538, in <module>
    cli()
  File "/usr/local/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 271, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 2
 See stacktrace above to identify the issue ((type:runtime.error)
```

**Comment by yveskerwyn** [comment]
This solves the problem:

```
g8client__cl:
  url: 'be-scale-1.demo.greenitglobe.com'
  login: 'cockpit_api_user'
  password: 'cockpit12345'
  account: 'Account of Artilium'

account__56e16382bc:
  g8client: 'cl'
  maxMemoryCapacity: 7
  maxCPUCapacity: 3
  maxNumPublicIP: 6
  maxDiskCapacity: 11
  description: 'Reseller 56e16382bc Created by newreseller'
  accountusers:
  - cockpit_api_user

actions:
  - action: install
```

So you need add a user explicitelly, otherwise it tries to delete the creating user (cockpit_api_user)
