### ISSUE TITLE
mvp-cockpit: Value type mismatch message isn't very helpful

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#82]
Context: Cockpit repository "yves06" on [Artilium Cockpit](https://gig.demo.greenitglobe.com/CBGrid/Virtual%20Machine?id=3856)

Something wrong with the blueprint? If yes, we need error messages helping to understand what actually is wrong...

Below screenshot of blueprints followed by stack trace:

![screen shot 2016-11-30 at 16 51 46](https://cloud.githubusercontent.com/assets/13795109/20759481/4f0e5a90-b71d-11e6-8b76-9f30550e1903.png)

```
Error of job: autosnapshotting!as (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/autosnapshotting/install.py", line 8, in action
    snapshot_action.period = j.data.types.duration.convertToSeconds(service.model.data.snapshotInterval)
  File "capnp/lib/capnp.pyx", line 1254, in capnp.lib.capnp._DynamicStructBuilder.__setattr__ (capnp/lib/capnp.cpp:28032)
  File "capnp/lib/capnp.pyx", line 1252, in capnp.lib.capnp._DynamicStructBuilder.__setattr__ (capnp/lib/capnp.cpp:27936)
  File "capnp/lib/capnp.pyx", line 1245, in capnp.lib.capnp._DynamicStructBuilder._set (capnp/lib/capnp.cpp:27574)
  File "capnp/lib/capnp.pyx", line 717, in capnp.lib.capnp._setDynamicField (capnp/lib/capnp.cpp:17333)
  File "capnp/lib/capnp.pyx", line 685, in capnp.lib.capnp._setBaseString (capnp/lib/capnp.cpp:16024)
capnp.lib.capnp.KjException: src/capnp/dynamic.c++:1691: failed: Value type mismatch.
stack: 0x7ff5f55f3b09 0x7ff5f55f773d 0x7ff5f55cda2c 0x7ff5f55ca219 0x7ff5f55cabc4 0x7ff5f55cc34b 0x7ff5f549075d 0x7ff5f54c4677 0x7ff5f54c7af5 0x7ff5f5453f8b 0x56f459 0x51b6b1 0x524c5b 0x4e39af 0x5bcf47 0x51cc77


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 490, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 246, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 1
 See stacktrace above to identify the issue ((type:runtime.error)
```

**Comment by xmonader** [comment]
I executed this blueprint
```
g8client__env1:
  url: 'du-conv-3.demo.greenitglobe.com'
  #url: 'gig.demo.greenitglobe.com'
  login: 'login'
  password: 'pass'
  account: 'account'

vdc__testsnap2:
  description: 'testsnap'
  g8client: env1
  location: 'du-conv-3'
  uservdc:
    - 'thabeta'

node.ovc__myn:
  os.image: 'Ubuntu 16.04 x64'
  bootdisk.size: 10
  sizeID: 2
  vdc: testsnap2

autosnapshotting__d5aef9bbef:
  vdc: testsnap2
  snapshotInterval: '2h'
  cleanupInterval: '1d'
  retention: '5d'
```
Didn't have any errors.

**Comment by yveskerwyn** [comment]
Closing since this error is old, probably impossible to reproduce
