### ISSUE TITLE
mvp-cockpit: TypeError when creating a disk.ovc service

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#92]
Blueprint:
```
disk.ovc__disk1:
  description: 'for testing purposes'
  size: 10

s3__s34yves02:
  vdc: vdc4yves02
  disk:
    - disk1
  domain: s34yves02.aydo2.com
```

Result when executing `ays blueprint`:
```
root@vm-61:/optvar/cockpit_repos/yves02# ays blueprint

**** TRACEBACK ***
File "/opt/jumpscale8//lib/JumpScale/data/serializers/SerializerYAML.py", line 17, in loads
    return yaml.load(s)
  File "/usr/local/lib/python3.5/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.5/dist-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 84, in compose_node


disk.ovc__disk1:
    node = self.compose_mapping_node(anchor)


  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib/python3.5/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib/python3.5/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python3.5/dist-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 149, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/usr/local/lib/python3.5/dist-packages/yaml/scanner.py", line 289, in stale_possible_simple_keys
    "could not find expected ':'", self.get_mark())
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 3, column 3:
      size = 10
      ^
could not find expected ':'
  in "<unicode string>", line 5, column 1:
    s3__s34yves02:
    ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 538, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 137, in blueprint
    repo.blueprintExecute(role=role, instance=instance, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 339, in blueprintExecute
    for bp in self.blueprints:
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 318, in blueprints
    for path, bp in self._load_blueprints().items():
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 309, in _load_blueprints
    bps[path] = Blueprint(self, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Blueprint.py", line 31, in __init__
    self.is_valid = self._validate_yaml(self.content)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Blueprint.py", line 253, in _validate_yaml
    raise j.exceptions.Input('Yaml format is not valid for %s please fix this to continue' % self.name)
JSExceptions.Input: ERROR: Yaml format is not valid for s3.yaml please fix this to continue ((type:input.error)
```

**Comment by yveskerwyn** [comment]
Solved by quoting domain name
