### ISSUE TITLE
mvp-cockpit: Image g8os-test-1604 not available

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#95]
When trying to install app_docker using following blueprint:

```
node.ovc__vm4docker:
  os.image: 'Ubuntu 16.04 x64'
  ports:
    - "7922:22"
    - "8080:80"
  bootdisk.size: 10
  memory: 2
  vdc: vdc4yves02

os.ssh.ubuntu__vm4docker:
  node: 'vm4docker'

app_docker__docker:
  os: vm4docker
```

When executing `ays run`:

```
root@vm-61:/optvar/cockpit_repos/yves02# ays run
Compute dependency graph...
RUN:ab400586ae182e7fcaaba1a3ed4d98ed
-------
## step:1

step:1 (new)
- node.ovc                  s34yves02                 ! install         (new)
- node.ovc                  vm4docker                 ! install         (new)

## step:2

step:2 (new)
- os.ssh.ubuntu             vm4docker                 ! install         (new)

## step:3

step:3 (new)
- app_docker                docker                    ! install         (new)


Do you want to execute this run ? (y/n):y
[Mon05 17:31] - ...umpScale/baselib/jobcontroller/Run.py:72   - INFO     - execute job: node.ovc!s34yves02 (install)
[Mon05 17:31] - ...umpScale/baselib/jobcontroller/Run.py:72   - INFO     - execute job: node.ovc!vm4docker (install)
[Mon05 17:31] - ...umpScale/baselib/jobcontroller/Run.py:100  - INFO     - stdout of job: node.ovc!vm4docker (install)
[Mon05 17:31] - ...umpScale/baselib/jobcontroller/Run.py:101  - INFO     - cloudspaceid:6 name:vm4docker size:6 image:2 disksize:10

[Mon05 17:31] - ...umpScale/baselib/jobcontroller/Run.py:101  - INFO     - root:x:0:0:root:/root:/bin/bash

[Mon05 17:32] - ...umpScale/baselib/jobcontroller/Run.py:101  - INFO     - {
   "blockdevices": [
      {"name": "sr0", "maj:min": "11:0", "rm": "1", "size": "368K", "ro": "0", "type": "rom", "mountpoint": null},
      {"name": "vda", "maj:min": "253:0", "rm": "0", "size": "10G", "ro": "0", "type": "disk", "mountpoint": null,
         "children": [
            {"name": "vda1", "maj:min": "253:1", "rm": "0", "size": "9.9G", "ro": "0", "type": "part", "mountpoint": "/"},
            {"name": "vda14", "maj:min": "253:14", "rm": "0", "size": "4M", "ro": "0", "type": "part", "mountpoint": null},
            {"name": "vda15", "maj:min": "253:15", "rm": "0", "size": "106M", "ro": "0", "type": "part", "mountpoint": "/boot/efi"}
         ]
      }
   ]
}

[Mon05 17:32] - ...umpScale/baselib/jobcontroller/Run.py:137  - INFO     - job job: node.ovc!vm4docker (install) done sucessfuly
Error of job: node.ovc!s34yves02 (install):
*TRACEBACK*********************************************************************************
Image g8os-test-1604 not available for vdc vdc4yves02


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 538, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 261, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 1
 See stacktrace above to identify the issue ((type:runtime.error)
```

**Comment by xmonader** [comment]
Most likely the image isn't available on the environment

**Comment by yveskerwyn** [comment]
Correct, and as discussed we at least need to have documented that there is a dependency on this image + instructions how to install it, or even better an actor that also takes care of the installation of this image if it is missing

**Comment by rkhamis** [comment]
Actor needs to be changed to use any base image and make sure its dependencies are met instead.
Fix will be forthcoming.

**Comment by yveskerwyn** [comment]
thanks @rkhamis, while waiting for this, where can I find this **g8os-test-1604** image?

using `ays list | grep g8os*` on the master Docker container didn't return anything, so `ays install -n g8os-test-1604 -tn stor-01.cl-g8-uk1` will not work

**Comment by rkhamis** [comment]
be-conv-2 on gig has it already.

**Comment by muhamadazmy** [comment]
Fixed
https://github.com/Jumpscale/ays_jumpscale8/blob/8.1.0/templates/app/s3/REAME.md

**Comment by yveskerwyn** [comment]
@muhamadazmy fixed = no dependency anymore on g8os-test-1604 image?

**Comment by rkhamis** [comment]
@yveskerwyn yes.
