### ISSUE TITLE
mvp-cockpit: unexpected error about 'empty' location when using S3 actor

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#96]
blueprint for creating the vdc:
```
g8client__cl:
  url: uk-g8-1.demo.greenitglobe.com
  login: yves
  password: IAM4greenIT
  account: Account of Yves

vdc__vdc4yves03:
  g8client: cl
  account: Account of Yves
  location: 'uk-g8-1'

actions:
  - action: install
```

blueprint for creating the S3 service:
```
disk.ovc__disk1:
  description: 'testing purposes'
  size: 10

s3__s34yves03:
  vdc: vdc4yves03
  disk:
    - disk1
  domain: 's3-yves03.aydo2.com'

actions:
  - action: install
```

Result when executing `ays blueprint`:
```
root@vm-61:/optvar/cockpit_repos/yves03# ays blueprint


[Tue06 10:23] - ...le/baselib/atyourservice81/Service.py:45   - INFO     - create service s34yves03 from s3


[Tue06 10:23] - ...le/baselib/atyourservice81/Service.py:45   - INFO     - create service auto_5 from vdc
Error of job: vdc!auto_5 (input):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 169, in executeInProcess
    res = self.method(job=self)
  File "/tmp/actions/vdc/input.py", line 7, in action
    raise j.exceptions.Input("location argument cannot be empty, cannot continue init of %s" % service)
JSExceptions.Input: ERROR: location argument cannot be empty, cannot continue init of service:vdc!auto_5 ((type:input.error)


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 538, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 137, in blueprint
    repo.blueprintExecute(role=role, instance=instance, path=path)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/AtYourServiceRepo.py", line 343, in blueprintExecute
    bp.load(role=role, instance=instance)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Blueprint.py", line 179, in load
    actor.serviceCreate(instance=bpinstance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 386, in serviceCreate
    service = Service(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 23, in __init__
    self._initFromActor(actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 95, in _initFromActor
    parent = self._initParent(actor, args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 136, in _initParent
    res.append(auto_actor.serviceCreate(instance="auto_%d" % instance, args={}))
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Actor.py", line 386, in serviceCreate
    service = Service(aysrepo=self.aysrepo, actor=self, name=instance, args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 23, in __init__
    self._initFromActor(actor, args=args, name=name)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 83, in _initFromActor
    args2 = self.input(args=args)
  File "/opt/jumpscale8/lib/JumpScale/baselib/atyourservice81/Service.py", line 519, in input
    args = job.executeInProcess()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Job.py", line 179, in executeInProcess
    raise j.exceptions.RuntimeError("could not execute job:%s" % self)
JSExceptions.RuntimeError: ERROR: could not execute job:job: vdc!auto_5 (input) ((type:runtime.error)
```

**Comment by yveskerwyn** [comment]
problem solved by executing the blueprints sequentially
