### ISSUE TITLE
mvp-cockpit: 400 Bad Request when deploying new VDC on be-conv-2

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/ays_jumpscale8#99]
blueprint: 
```
g8client__cl:
  url: gig.demo.greenitglobe.com
  login: yves
  password: IAM4greenIT
  account: centrilogic

vdc__vdc4yves03:
  g8client: cl
  account: centrilogic
  location: 'be-conv-2'

actions:
  - action: install
```

after succesfully executing `ays blueprint` executing `ays run` fails:
```
root@vm-61:/optvar/cockpit_repos/yves03# ays run
Compute dependency graph...
RUN:8157ffb4da7d5ba874928ee3d4716638
-------
## step:1



step:1 (new)
- vdcfarm                   auto_2                    ! install         (new)
- g8client                  cl                        ! install         (new)

## step:2

step:2 (new)
- vdc                       vdc4yves03                ! install         (new)


Do you want to execute this run ? (y/n):y
[Tue06 13:22] - ...umpScale/baselib/jobcontroller/Run.py:72   - INFO     - execute job: vdcfarm!auto_2 (install)
[Tue06 13:22] - ...umpScale/baselib/jobcontroller/Run.py:72   - INFO     - execute job: g8client!cl (install)
[Tue06 13:22] - ...umpScale/baselib/jobcontroller/Run.py:137  - INFO     - job job: vdcfarm!auto_2 (install) done sucessfuly
[Tue06 13:22] - ...umpScale/baselib/jobcontroller/Run.py:137  - INFO     - job job: g8client!cl (install) done sucessfuly
[Tue06 13:22] - ...umpScale/baselib/jobcontroller/Run.py:72   - INFO     - execute job: vdc!vdc4yves03 (install)
Error of job: vdc!vdc4yves03 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/opt/jumpscale8//lib/JumpScale/core/processmanager/ProcessManagerFactory.py", line 195, in start
    res = self.method(**self.args)
  File "/tmp/actions/vdc/install.py", line 10, in action
    acc = cl.account_get(service.model.data.account)
  File "/opt/jumpscale8//lib/JumpScale/clients/openvcloud/Client.py", line 147, in account_get
    maxNumPublicIP=maxNumPublicIP)
  File "/opt/jumpscale8/lib/JumpScale/clients/portal/PortalClient.py", line 43, in __call__
    raise ApiError(response)
JumpScale.clients.portal.PortalClient.ApiError: 400 Bad Request
Param with name:location is missing.


******************************************************************************************


**** TRACEBACK ***
Traceback (most recent call last):
  File "/opt/jumpscale8/bin/ays", line 538, in <module>
    cli()
  File "/opt/jumpscale8/bin/ays", line 46, in run
    run.execute()
  File "/opt/jumpscale8/lib/JumpScale/baselib/jobcontroller/Run.py", line 261, in execute
    raise j.exceptions.RuntimeError("Error during execution of step %d\n See stacktrace above to identify the issue" % step.dbobj.number)
JSExceptions.RuntimeError: ERROR: Error during execution of step 2
 See stacktrace above to identify the issue ((type:runtime.error)
```

**Comment by rkhamis** [comment]
According to @grimpy that's because this is an old env.
